### ISSUE TITLE
The "postexpirator-sidebar" plugin has encountered an error and cannot be rendered.

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Future#389] opened 2023-02-14 22:24 UTC
Got this error when editing back some posts while using Pro version:
<img width="1428" alt="Screen Shot 2023-02-14 at 16 12 29" src="https://user-images.githubusercontent.com/4999794/218876507-07240e0a-e69f-4466-b236-aa831e070dfa.png">

```
TypeError: a is null
value gutenberg-panel.jsx:237
value gutenberg-panel.jsx:32
```

Error remains if I switch to free.

**Comment by htmgarcia** [comment] 2023-02-14 22:59
Checking the log debug, I see a few records that seems to delete the custom meta:
As example: `DEBUG: 56 -> EXPIRATION DATA REMOVED from the post`

I'm not sure at which point this happened. Certainly I was playing with the expiration settings in post edit and this deletion was triggered when I did schedule changes.

**Comment by andergmartins** [comment] 2023-02-15 12:24
Thanks @htmgarcia, I can't replicate that JS error yet, but I will try a little more. Please, could you check if you see the same error using a instawp site? 

Btw, if the post was saved without the metabox there (blocked by that error), there is a chance  the plugin understood you unselected the checkbox disabling the expiration, and removed the data. I will try replicating that as well.

**Comment by andergmartins** [comment] 2023-02-15 12:27
@htmgarcia please, could you try running this on the console after that error happens?
```js
wp.data.select('core/editor').getEditedPostAttribute('meta')
```

**Comment by htmgarcia** [comment] 2023-02-15 14:21
@andergmartins sorry, not able to even reproduce the issue with new posts in the same site.

The output is:
```
{
  "advgb_blocks_editor_width": "",
  "advgb_blocks_columns_visual_guide": "",
  "_expiration-date-status": "saved",
  "_expiration-date": 1700599020,
  "_expiration-date-type": "draft",
  "_expiration-date-categories": null,
  "_expiration-date-options": {
    "expireType": "draft",
    "category": [
      ""
    ],
    "categoryTaxonomy": "category",
    "id": 56
  }
}
```

**Comment by andergmartins** [comment] 2023-02-15 14:32
Thanks, @htmgarcia there is a chance that was an issue caused by a cached JS script. I will close it for now considering none of us can replicate it anymore. We can reopen it later if we see it again.

**Closed by andergmartins** 2023-02-15 14:32 UTC
Labels: unconfirmed bug
