### ISSUE TITLE
Expire Date only available between 1970 and 1980

### ISSUE THREAD

**Issue by doeneranimal** [publishpress/PublishPress-Future#495] opened 2023-07-06 09:20 UTC
Zukünftige Aktionen aktivieren

Jahr 1970

Monat

Tag

Stunde (CET)

Minute

There is only 1970 up to 1980 possible to pick.

Version 3.0.4, also two versions before

**Comment by andergmartins** [comment] 2023-07-10 19:33
Hi @doeneranimal, 
Please could you add more details? I can't replicate this issue.
Do you have a screenshot?

**Comment by rizaardiyanto1412** [comment] 2023-07-11 14:05
Another user is facing this issue, and they are asking if it needs to enable some PHP setting. What do you think @andergmartins ?

https://wordpress.org/support/topic/available-years/

**Comment by doeneranimal** [comment] 2023-07-11 17:08
Hi Riza,

i'm on php 8.2, tried out now 8.1 and 8.0. No changes.

Sicher versendet mit [Proton Mail](https://proton.me/).

------- Original Message -------
Riza Maulana Ardiyanto ***@***.***> schrieb am Dienstag, 11. Juli 2023 um 16:06:

**Comment by andergmartins** [comment] 2023-07-11 20:29
@doeneranimal thanks for the details. 

I think the problem is coming from a corrupted date in the post, or empty date value, that when converted by `$gmDate = gmdate('Y-m-d H:i:s', $postMetaDate);` it returns an invalid date. 1970 is the first year of Unix Time. 

But I still can't replicate this. Please, could you let us know if that happens for new posts, or only when editing posts? If so, please could you send us an screenshot of the Post Types tab in the settings page?

**Comment by usrve** [comment] 2023-07-12 07:35
Hello!
I am the user whose Riza was referring to.
I should point out that everything worked fine in my environment up until the last update. I didn't make any other changes.
In Block mode and Quick Edit everything works fine, since it use a predefined text field that can be manually changed. But with Classic Editor there's only the dropdown command.....
The issue happens in Classic Editor both in new posts and when editing an old one where the expiration date was not set. But if I Quick Edit a post and manually add the correct year, than save and Edit in "normal mode" again the dropdown shows years from 2023 to 2033, as it should. 

Here is the screenshot of the Post Type tab in settings page (localization is Italian):
![Future years settings](https://github.com/publishpress/PublishPress-Future/assets/139324328/f3c88c45-c8b5-47bd-9586-6fc1c55253de)

**Comment by usrve** [comment] 2023-07-12 07:46
I also have a custom post type that has a different setting:
![Future years settings notif](https://github.com/publishpress/PublishPress-Future/assets/139324328/59f6be0c-f768-49b9-9537-0dc3b48b3ad0)
If I add a new custom post it should make default expiration "+60 day" from today but instead it shows these settings (3 days ago):
![Future years settings](https://github.com/publishpress/PublishPress-Future/assets/139324328/3533bd3d-21f8-4013-9cfe-19d99ea0be70)
Thanks!

**Comment by doeneranimal** [comment] 2023-07-12 07:53
Hello,

same problem and workaround here. Localization is german.

------- Original Message -------
usrve ***@***.***> schrieb am Mittwoch, 12. Juli 2023 um 09:35:

**Comment by andergmartins** [comment] 2023-07-12 16:05
Hi guys, @doeneranimal @usrve that makes sense, thanks. I think the problem is that the date function is not able to calculate the date using no-english terms. I will make more tests to see if we can fix that, but please, could you try changing the default date offset to something in English? `+90 days` or `+1 day` for example. On both the general setting (Defaults tab) or Post type, please.

Thanks

**Comment by doeneranimal** [comment] 2023-07-13 07:19
Did what you say and it works for me. Made the parameters in english ( " +2 month" instead of "+2 Monat"). Moved the general language from german to english and back to german. Now the actually date is shown in the box.

Perhaps a problem with the translation?

------- Original Message -------
Anderson Grüdtner Martins ***@***.***> schrieb am Mittwoch, 12. Juli 2023 um 18:05:

**Comment by usrve** [comment] 2023-07-13 08:42
Your workaround work for me too! I changed "nessuno" to "+0 days" and "+60 giorni" to "+60 days" and everything is back to normal.
But I can assure you that the previous setting was working for me up until the last update.
Maybe you changed some parameters in the date function?

**Comment by andergmartins** [comment] 2023-07-13 16:49
Thanks, guys.
Yes, we needed to refactor a few methods and now we rely on a function that only supports English terms. We have changed the field description mentioning that. Please, keep those settings in English from now. 

I'm closing this but feel free to comment if you have any questions.

**Closed by andergmartins** 2023-07-13 16:49 UTC
Labels: unconfirmed bug
