### ISSUE TITLE
Expose wrappers for legacy functions

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#40] opened 2021-06-11 21:54 UTC
Let's add support for this legacy function:
https://wordpress.org/support/topic/programmatic-setup-error-in-v2-4-2/

**Comment by contactashish13** [comment] 2021-06-14 06:02
@stevejburge I think a big part of the problem is that since the plugin does not follow OOP principles, all the functions are publicly exposed and thus fair game for anyone who wants to hook in. To prevent misuse, I have marked all the functions we use as `@internal` and `@access private` so that the user is aware that these are internal functions and can change in the future. Have also provided wrappers for 3 important legacy functions that we changed. 

PR: https://github.com/publishpress/PublishPress-Future/pull/42

Going forward, it would be a good idea to convert this into a class and then make internal methods private.

**Comment by stevejburge** [comment] 2021-06-14 14:17
@contactashish13 Good idea, thanks

**Comment by contactashish13** [comment] 2021-07-01 04:16
@stevejburge this is fixed by #42

**Closed** 2021-07-07 04:10 UTC
Labels: bug
