### ISSUE TITLE
Category replace not working with new Gutenberg box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#127] opened 2021-09-17 17:05 UTC
> "category replace" does not work when the "Gutenberg style box" is selected in the settings. When the "Classic style box" is selected the "category replace" works fine.

https://wordpress.org/support/topic/gutenberg-style-box-does-not-seem-to-work/

**Comment by contactashish13** [comment] 2021-09-21 09:03
@stevejburge this looks like a duplicate of #128.

**Comment by stevejburge** [comment] 2021-09-29 14:45
One more report https://wordpress.org/support/topic/posts-expiring-at-random-times/#post-14918385

> It seems to happen only when posts are set to expire to a category, not a change in post status.

**Closed** 2021-10-07 20:39 UTC
Labels: bug, Gutenberg
