### ISSUE TITLE
post expiring one year early

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Future#24] opened 2021-05-22 23:05 UTC
https://wordpress.org/support/topic/edited-post-expiry-dates-expiring-on-original-date/

> I think this may be the issue I am seeing as well. We’ve tracked a number of posts that have expired exactly one year early. We do update expiration dates for these posts (which are paid business listings) on an annual basis, so it is likely that the posts that expired had renewed and had their expiration date updated.
> 
> Over this past weekend, a listing that had an expiration date of May 5, 2022 was expired on May 5, 2021. I have verified that the value in the postmeta table for ‘_expiration-date’ both before and after May 5, 2021 was ‘1651769880’, which is correct for May 5, 2022. I do not have database backups that go back a year, but the post_date on this listing was in May 2018, so it has definitely had its expiration date modified on at least one occasion.
>

**Comment by contactashish13** [comment] 2021-05-24 12:55
@stevejburge unfortunately, I'm unable to reproduce this behavior. This is likely related to #6

**Comment by stevejburge** [comment] 2021-05-24 13:41
@contactashish13 Thanks. I asked the original reporter for more details

**Comment by stevejburge** [comment] 2021-06-16 21:14
@contactashish13 More details posted:

> I believe I have found the issue. I tested this on the Twenty Twenty-One theme with no other plugins active.
> 
> The year dropdown in the Post Expirator metabox is not updating to the correct year (as stored in the database) and is instead falling back to the first option, which is always the current year, so if you then do any other update, it changes your expiration date in the database to the current year.
> 
> I verified that when you change the date, setting the selects and text inputs to, say, 2024 June 16 @ 12:19 and update, the _expiration-date for that post in the postmeta table correctly becomes 1718554740. If I reload the post edit page, the post expirator form now reads 2021 June 16 @ 12:19, which is what gets saved to the _expiration-date postmeta field as 1623860340 if I update the post.
> 
> The month and hour selects work correctly. It is only the year select that is not updating to the value from the database.

**Comment by stevejburge** [comment] 2021-06-16 21:21
We also have similar feedback here:

> If the meta value “_expiration-date” hast the value “1658966340” Which would be equal to “Jul 27 2022” the “Post Expirator Box” while editing the post will display “Jul 27 2021” instead of “2022” if you save or update the post the next time it will decrease the “_expiration-date” to 1627430340 and the Post will be deleted one year earlier.

https://wordpress.org/support/topic/displayed-date-in-editor-has-wrong-year/

**Comment by contactashish13** [comment] 2021-06-17 02:58
@stevejburge the last 2 comments point out the the bug caused by #39 which also affects this feature. Both the issues are addressed by #41. 

But the original issue in https://wordpress.org/support/topic/edited-post-expiry-dates-expiring-on-original-date/ was reported 5 months ago and predates the new bug we introduced so I wouldn't close this issue yet.

**Comment by holzhannes** [comment] 2021-06-17 07:28
Reading the issue reports of #39 and #41, from my point of view they are all fixed by PR #48. The Problem was just, that the dropdown list for the years was created but without preselecting a specific year, and therefore it was always the current year.

**Comment by contactashish13** [comment] 2021-06-17 10:03
@holzhannes if you look at https://github.com/publishpress/PublishPress-Future/pull/41/files#diff-cbad8a0f4ee75b07aa33761be03e84f3d1196863f60e6fbe01f329c831f23211R372 it is the same as what you have uncovered so #41 fixes it

**Comment by contactashish13** [comment] 2021-07-01 04:17
@stevejburge this is fixed by #41

**Closed** 2021-07-07 04:10 UTC
Labels: bug
